services:
  http-server:
    image: ronaksingh2006/inkcalibur-http-server:latest
    ports:
      - "3001:3001"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}

  ws-server:
    image: ronaksingh2006/inkcalibur-ws-server:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}

  frontend:
    image: ronaksingh2006/inkcalibur-frontend:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - http-server
      - ws-server
    environment:
      BACKEND_URL: http://http-server:3001
      WS_URL: ws://ws-server:8080