FROM node:22-alpine

WORKDIR /inkalibur

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY apps/http-server ./apps/http-server
COPY packages ./packages

RUN npm install -g pnpm
RUN pnpm install

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

RUN pnpm run db:generate
RUN pnpm --filter http-server build

EXPOSE 3001

CMD ["pnpm", "run", "start:http-server"]