FROM node:22-alpine
WORKDIR /inkalibur

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY apps/ws-server ./apps/ws-server
COPY packages ./packages

RUN npm install -g pnpm
RUN pnpm install

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

RUN pnpm run db:generate

RUN pnpm --filter ws-server build
EXPOSE 8080

CMD ["pnpm", "run", "start:ws-server"]